<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="RegistrationCommonApi"
                  targetNamespace="http://test-soap.com/api/registration"
                  xmlns:tns="http://test-soap.com/api/registration"
                  xmlns:registrationMessages="http://test-soap.com/api/registration/messages"
                  xmlns:commonMessages="http://test-soap.com/api/common/messages"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
>

  <wsdl:documentation>Registration Web Service Definition</wsdl:documentation>

  <wsdl:types>
    <xsd:schema targetNamespace="http://test-soap.com/api/registration" elementFormDefault="qualified">
      <xsd:import namespace="http://test-soap.com/api/registration/messages" schemaLocation="registration-messages-common.xsd"/>
      <xsd:import namespace="http://test-soap.com/api/common/messages" schemaLocation="common-messages.xsd"/>
      <xsd:import namespace="http://test-soap.com/api/common/types" schemaLocation="common-types.xsd"/>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="registerUserRequestMessage">
    <wsdl:part name="registerUserRequest" element="registrationMessages:registerUserRequest"/>
  </wsdl:message>
  <wsdl:message name="registerUserResponseMessage">
    <wsdl:part name="registerUserResponse" element="registrationMessages:registerUserResponse"/>
  </wsdl:message>

  <wsdl:portType name="registrationCommonPortType">

    <wsdl:operation name="registerUser">
      <wsdl:input name="registerUserRequestMessage" message="tns:registerUserRequestMessage"/>
      <wsdl:output name="registerUserResponseMessage" message="tns:registerUserResponseMessage"/>
      <wsdl:fault name="errorDetail" message="tns:errorDetailMessage"/>
    </wsdl:operation>

  </wsdl:portType>

  <wsdl:binding name="registrationCommonHttpSoapBinding" type="tns:registrationCommonPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

    <wsdl:operation name="registerUser">
      <soap:operation soapAction="http://test-soap.com/api/registration/registerCUser"/>
      <wsdl:input>
        <soap:body parts="registerUserRequest" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="registerUserResponse" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="errorDetail">
        <soap:fault name="errorDetail" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>

  </wsdl:binding>

  <wsdl:service name="registrationCommon">
    <wsdl:port name="registrationCommonHttpSoapPort" binding="tns:registrationCommonHttpSoapBinding">
      <soap:address location="https://{{SERVER}}/api/api/v5/registration"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
