<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="http://www.OneWay.com" xmlns:n="http://www.OneWay.com/Name/Types" xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/" targetNamespace="http://www.OneWay.com">
    <wsdl:types>
        <xs:schema targetNamespace="http://www.OneWay.com/Name/Types" elementFormDefault="qualified">
            <xs:element name="OneWayRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="OneWayField" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="OneWayRequest">
        <wsdl:part name="OneWayRequest" element="n:OneWayRequest"/>
    </wsdl:message>

    <wsdl:portType name="OneWayPortType">
        <wsdl:operation name="OneWay">
            <wsdl:input message="tns:OneWayRequest"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="OneWayBinding" type="tns:OneWayPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="OneWay">
            <soap:operation soapAction="http://www.OneWay.com#OneWay" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="OneWayService">
        <wsdl:port name="OneWayPortType" binding="tns:OneWayBinding">
            <soap:address location="http://www.OneWay.com/"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
