<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:tns="urn:platform_2013_2.webservices.netsuite.com" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:platformMsgs="urn:messages_2013_2.platform.webservices.netsuite.com" xmlns:platformFaults="urn:faults_2013_2.platform.webservices.netsuite.com" targetNamespace="urn:platform_2013_2.webservices.netsuite.com">
    <types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
            <xsd:import namespace="urn:core_2013_2.platform.webservices.netsuite.com" schemaLocation="soap.platform.core.xsd"/>
            <xsd:import namespace="urn:messages_2013_2.platform.webservices.netsuite.com" schemaLocation="soap.platform.messages.xsd"/>
		</xsd:schema>
    </types>
    <message name="loginRequest">
        <part name="parameters" element="platformMsgs:login"/>
    </message>
    <message name="loginResponse">
        <part name="parameters" element="platformMsgs:loginResponse"/>
    </message>
    <portType name="NetSuitePortType">
        <operation name="login">
            <input name="loginRequest" message="tns:loginRequest"/>
            <output name="loginResponse" message="tns:loginResponse"/>
        </operation>
    </portType>
	<binding name="NetSuiteBinding" type="tns:NetSuitePortType">
        <SOAP-ENV:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="login">
            <SOAP-ENV:operation soapAction="login"/>
            <input name="loginRequest">
                <SOAP-ENV:body use="literal"/>
            </input>
            <output name="loginResponse">
                <SOAP-ENV:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="NetSuiteService">
        <port name="NetSuitePort" binding="tns:NetSuiteBinding">
            <SOAP-ENV:address location="http://localhost:1509"/>
        </port>
    </service>
</definitions>
