<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:tns="urn:platform_2013_2.webservices.netsuite.com" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:platformMsgs="urn:messages_2013_2.platform.webservices.netsuite.com" xmlns:platformFaults="urn:faults_2013_2.platform.webservices.netsuite.com" targetNamespace="urn:platform_2013_2.webservices.netsuite.com">
    <types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
            <xsd:import namespace="urn:core_2013_2.platform.webservices.netsuite.com" schemaLocation="soap.platform.core.xsd"/>
            <xsd:import namespace="urn:messages_2013_2.platform.webservices.netsuite.com" schemaLocation="soap.platform.messages.xsd"/>
            <xsd:import namespace="urn:relationships_2013_2.lists.webservices.netsuite.com" schemaLocation="soap.lists.relationships.xsd"/>
		</xsd:schema>
    </types>
    <message name="addListRequest">
        <part name="parameters" element="platformMsgs:addList"/>
    </message>
    <message name="addListResponse">
        <part name="parameters" element="platformMsgs:addListResponse"/>
    </message>
    <portType name="NetSuitePortType">
        <operation name="addList">
            <input name="addListRequest" message="tns:addListRequest"/>
            <output name="addListResponse" message="tns:addListResponse"/>
        </operation>
    </portType>
	<binding name="NetSuiteBinding" type="tns:NetSuitePortType">
        <SOAP-ENV:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <operation name="addList">
            <SOAP-ENV:operation soapAction="addList"/>
            <input name="addListRequest">
                 <SOAP-ENV:body use="literal"/>
            </input>
            <output name="addListResponse">
                <SOAP-ENV:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="NetSuiteService">
        <port name="NetSuitePort" binding="tns:NetSuiteBinding">
            <SOAP-ENV:address location="http://localhost:1509"/>
        </port>
    </service>
</definitions>
