<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.dummy.com"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:dummy="http://www.dummy.com/Types"
                  xmlns:tns="http://www.dummy.com">
    <wsdl:types>
        <xs:schema targetNamespace="http://www.dummy.com/Types"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:dummy="http://www.dummy.com/Types"
                   elementFormDefault="qualified" attributeFormDefault="unqualified">
            <xs:include schemaLocation="types_inline_xmlns.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="DummyRequest">
        <wsdl:part name="DummyRequest" element="dummy:DummyRequest"/>
    </wsdl:message>
    <wsdl:message name="DummyResponse">
        <wsdl:part name="DummyResponse" element="dummy:DummyResponse"/>
    </wsdl:message>
    <wsdl:portType name="DummyPortType">
        <wsdl:operation name="Dummy">
            <wsdl:input message="tns:DummyRequest"/>
            <wsdl:output message="tns:DummyResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="DummyBinding" type="tns:DummyPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Dummy">
            <soap:operation soapAction="tns#Dummy" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="DummyService">
        <wsdl:port name="DummyPortType" binding="tns:DummyBinding">
            <soap:address location="http://www.dummy.com/"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
