<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="Service" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://tempuri.org/"
    xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
    xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
	<wsdl:types>
		<xsd:schema targetNamespace="http://tempuri.org/Imports">
			<xsd:import schemaLocation="./childs/childxs0.wsdl" namespace="http://tempuri.org/" />
			<xsd:import schemaLocation="./childs/childxs7.wsdl" namespace="http://tempuri.org/FareQuote" />
			<xsd:import schemaLocation="./childs/childxs9.wsdl" namespace="http://tempuri.org/Request" /></xsd:schema>
	</wsdl:types>
	<wsdl:message name="Service_RetrieveFareQuoteDateRange_InputMessage">
		<wsdl:part name="parameters" element="tns:RetrieveFareQuoteDateRange" /></wsdl:message>
	<wsdl:message name="Service_RetrieveFareQuoteDateRange_OutputMessage">
		<wsdl:part name="parameters" element="tns:RetrieveFareQuoteDateRangeResponse" /></wsdl:message>
	<wsdl:portType name="Service">
		<wsdl:operation name="RetrieveFareQuoteDateRange">
			<wsdl:input wsaw:Action="http://tempuri.org/Service/RetrieveFareQuoteDateRange" message="tns:Service_RetrieveFareQuoteDateRange_InputMessage"
			/>
			<wsdl:output wsaw:Action="http://tempuri.org/Service/RetrieveFareQuoteDateRangeResponse" message="tns:Service_RetrieveFareQuoteDateRange_OutputMessage"
			/></wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="BasicHttpBinding_Service" type="tns:Service">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="RetrieveFareQuoteDateRange">
			<soap:operation soapAction="http://tempuri.org/Service/RetrieveFareQuoteDateRange" style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Service">
		<wsdl:port name="BasicHttpBinding_Service" binding="tns:BasicHttpBinding_Service">
			<soap:address location="http://tempuri.org/Service.Pricing.svc" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
