<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:typens="urn:Magento" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Magento" targetNamespace="urn:Magento">
   <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
          <complexType name="FixedArray">
            <complexContent>
               <restriction base="soapenc:Array">
                  <attribute ref="soapenc:arrayType" wsdl:arrayType="xsd:anyType[]" />
               </restriction>
            </complexContent>
         </complexType>
      </schema>
   </types>
   <message name="multiCall">
      <part name="sessionId" type="xsd:string" />
      <part name="calls" type="typens:FixedArray" />
      <part name="options" type="xsd:anyType" />
   </message>
   <message name="multiCallResponse">
      <part name="multiCallReturn" type="typens:FixedArray" />
   </message>
   <portType name="Mage_Api_Model_Server_HandlerPortType">
      <operation name="multiCall">
         <documentation>Multiple calls of resource functionality</documentation>
         <input message="typens:multiCall" />
         <output message="typens:multiCallResponse" />
      </operation>
   </portType>
   <binding name="Mage_Api_Model_Server_HandlerBinding" type="typens:Mage_Api_Model_Server_HandlerPortType">
      <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
       <operation name="multiCall">
         <soap:operation soapAction="urn:Mage_Api_Model_Server_HandlerAction" />
         <input>
            <soap:body namespace="urn:Magento" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
         </input>
         <output>
            <soap:body namespace="urn:Magento" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
         </output>
      </operation>
   </binding>
   <service name="MagentoService">
      <port name="Mage_Api_Model_Server_HandlerPort" binding="typens:Mage_Api_Model_Server_HandlerBinding">
         <soap:address location="http://localhost/index.php/api/index/index/" />
      </port>
   </service>
</definitions>