<definitions name = "MTOMService"
   targetNamespace = "http://www.examples.com/wsdl/MTOMService.wsdl"
   xmlns = "http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap = "http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:tns = "http://www.examples.com/wsdl/MTOMService.wsdl"
   xmlns:xsd = "http://www.w3.org/2001/XMLSchema">
 
   <message name = "DummyRequest">
      <part name = "param" type = "xsd:string"/>
   </message>
	
   <message name = "MTOMResponse">
      <part name = "attachment1" type = "xsd:base64Binary" />
      <part name = "attachment2" type = "xsd:base64Binary" />
   </message>

   <portType name = "MTOM_PortType">
      <operation name = "getAttachments">
         <input message = "tns:DummyRequest"/>
         <output message = "tns:MTOMResponse"/>
      </operation>
   </portType>

   <binding name = "MTOM_Binding" type = "tns:MTOM_PortType">
      <soap:binding style = "rpc"
         transport = "http://schemas.xmlsoap.org/soap/http"/>
      <operation name = "getAttachments">
         <soap:operation soapAction = "getAttachments"/>
         <input>
            <soap:body
               encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"
               namespace = "urn:examples:MTOMService"
               use = "encoded"/>
         </input>
		
         <output>
            <soap:body
               encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"
               namespace = "urn:examples:MTOMService"
               use = "encoded"/>
         </output>
      </operation>
   </binding>

   <service name = "MTOM_Service">
      <documentation>WSDL File for MTOMService</documentation>
      <port binding = "tns:MTOM_Binding" name = "MTOM_Port">
         <soap:address
            location = "http://www.examples.com/MTOMRequest/" />
      </port>
   </service>
</definitions>