<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/wsdl-viewer.xsl"?>
<wsdl:definitions xmlns:foo="http://fo.bar/doIt/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  name="doIt" targetNamespace="http://foo.bar/doIt">

    <wsdl:portType name="doIt">
        <wsdl:operation name="doItMan"/>
    </wsdl:portType>

    <wsdl:binding name="doItSOAP" type="foo:doIt">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="doIt">
            <soap:operation soapAction="" />
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="doIt">
        <wsdl:port binding="auth:doItSOAP" name="doItSOAP">
            <soap:address location="https://foo.bar/services/doIt/" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
