<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="IUserRemoteService" targetNamespace="http://example.com/" xmlns:ns1="http://example.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xs:schema elementFormDefault="unqualified" targetNamespace="http://example.com/" version="1.0" xmlns:tns="http://example.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="./xsd.xsd" namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>

<xs:element name="getLatestVersion" type="tns:getLatestVersion" />
<xs:element name="getLatestVersionResponse" type="tns:getLatestVersionResponse" />

<xs:complexType name="getLatestVersion">
<xs:sequence />
</xs:complexType>
<xs:complexType name="getLatestVersionResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="xs:long" />
</xs:sequence>
</xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="getLatestVersion">
    <wsdl:part element="ns1:getLatestVersion" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getLatestVersionResponse">
<wsdl:part element="ns1:getLatestVersionResponse" name="parameters"></wsdl:part>
</wsdl:message>
  <wsdl:portType name="IUserRemoteService">
    <wsdl:operation name="getLatestVersion">
      <wsdl:input message="ns1:getLatestVersion" name="getLatestVersion">
    </wsdl:input>
      <wsdl:output message="ns1:getLatestVersionResponse" name="getLatestVersionResponse">
    </wsdl:output>
    </wsdl:operation>
    
  </wsdl:portType>
</wsdl:definitions>
