<?xml version='1.0' encoding='UTF-8' ?>
<definitions
	name='no-params'
	targetNamespace='http://tempuri.org/no-params/wsdl/'
	xmlns:wsdlns='http://tempuri.org/no-params/wsdl/'
	xmlns:typens='http://tempuri.org/no-params/type/'
	xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
	xmlns:xsd='http://www.w3.org/2001/XMLSchema'
	xmlns:stk='http://schemas.microsoft.com/soap-toolkit/wsdl-extension'
	xmlns:dime='http://schemas.xmlsoap.org/ws/2002/04/dime/wsdl/'
	xmlns:ref='http://schemas.xmlsoap.org/ws/2002/04/reference/'
	xmlns:content='http://schemas.xmlsoap.org/ws/2002/04/content-type/'
	xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
	xmlns='http://schemas.xmlsoap.org/wsdl/'>

	<types>
		<schema
			targetNamespace='http://tempuri.org/no-params/type/'
			xmlns='http://www.w3.org/2001/XMLSchema'
			xmlns:SOAP-ENC='http://schemas.xmlsoap.org/soap/encoding/'
			xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
			elementFormDefault='qualified'>

			<import namespace='http://schemas.xmlsoap.org/soap/encoding/'/>
			<import namespace='http://schemas.xmlsoap.org/wsdl/'/>
			<import namespace='http://schemas.xmlsoap.org/ws/2002/04/reference/'/>
			<import namespace='http://schemas.xmlsoap.org/ws/2002/04/content-type/'/>

		</schema>
	</types>

	<message name='no-params.NoParams'>
	</message>

	<message name='no-params.NoParamsResponse'>
		<part name='Result' type='xsd:string'/>
	</message>

	<portType name='Port'>

		<operation name='NoParams' parameterOrder=''>
			<input message='wsdlns:no-params.NoParams'/>
			<output message='wsdlns:no-params.NoParamsResponse'/>
		</operation>

	</portType>

	<binding name='Binding' type='wsdlns:Port' >

		<stk:binding preferredEncoding='UTF-8'/>
		<soap:binding style='rpc' transport='http://schemas.xmlsoap.org/soap/http'/>

		<operation name='NoParams'>
			<soap:operation soapAction='http://tempuri.org/no-params/action/no-params.NoParams'/>
			<input>
				<soap:body
					use='encoded'
					encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/>
			</input>
			<output>
				<soap:body
					use='encoded'
		  		encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'
					parts='Result'/>
			</output>
		</operation>

	</binding>

	<service name='no-params' >
		<port name='Port' binding='wsdlns:Binding' >
		</port>
	</service>

</definitions>
