<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="CyberSourceTransactionWS" targetNamespace="urn:schemas-cybersource-com:transaction-data:TransactionProcessor" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:schemas-cybersource-com:transaction-data:TransactionProcessor" xmlns:data="urn:schemas-cybersource-com:transaction-data-1.26">
   <wsdl:types>
      <xsd:schema>
         <xsd:import namespace="urn:schemas-cybersource-com:transaction-data-1.26" schemaLocation="CyberSourceTransaction_1.26.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="messageIn">
      <wsdl:part name="input" element="data:requestMessage"/>
   </wsdl:message>
   <wsdl:message name="messageOut">
      <wsdl:part name="result" element="data:replyMessage"/>
   </wsdl:message>
   <wsdl:portType name="ITransactionProcessor">
      <wsdl:operation name="runTransaction">
         <wsdl:input name="inputMessageIn" message="tns:messageIn"/>
         <wsdl:output name="outputMessageOut" message="tns:messageOut"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="ITransactionProcessor" type="tns:ITransactionProcessor">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="runTransaction">
         <soap:operation soapAction="runTransaction" style="document"/>
         <wsdl:input name="inputMessageIn">
            <soap:body use="literal" namespace="urn:schemas-cybersource-com:transaction-data-1.26"/>
         </wsdl:input>
         <wsdl:output name="outputMessageOut">
            <soap:body use="literal" namespace="urn:schemas-cybersource-com:transaction-data-1.26"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="TransactionProcessor">
      <wsdl:documentation>CyberSource Web Service</wsdl:documentation>
      <wsdl:port name="portXML" binding="tns:ITransactionProcessor">
         <soap:address location="https://ics2wstest.ic3.com/commerce/1.x/transactionProcessor"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>