<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    targetNamespace="http://www.Dummy.com"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:dummy="http://www.Dummy.com"
    xmlns:tns="http://www.Dummy.com">
    <wsdl:types>
        <xsd:schema
            targetNamespace="http://www.Dummy.com"
            xmlns:common="http://www.Dummy.com/Common"
            elementFormDefault="qualified" attributeFormDefault="unqualified">
            <xsd:import namespace="http://www.Dummy.com/Common" schemaLocation="common.xsd"/>
            <xsd:element name="DummyRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element ref="common:Order"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="DummyResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element ref="common:Result"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </wsdl:types>
	<wsdl:message name="DummyRequest">
		<wsdl:part name="parameters" element="dummy:DummyRequest"/>
	</wsdl:message>
	<wsdl:message name="DummyResponse">
		<wsdl:part name="parameters" element="dummy:DummyResponse"/>
	</wsdl:message>
	<wsdl:portType name="DummyPortType">
		<wsdl:operation name="Dummy">
			<wsdl:input message="tns:DummyRequest"/>
			<wsdl:output message="tns:DummyResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="DummyBinding" type="tns:DummyPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="Dummy">
			<soap:operation soapAction="http://www.Dummy.com#Dummy" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="DummyService">
		<wsdl:port name="DummyPortType" binding="tns:DummyBinding">
			<soap:address location="http://www.Dummy.com/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
